### PR TITLE
Add a variable to get the weather duration

### PR DESCRIPTION
**Pull request by montlikadani**

### CODE REVIEW

**Comment by montlikadani** [comment]
Should I add `getThunderDuration()` variable?

**Comment by extendedclip** [comment]
What is the output of weatherDuration? Also when was that introduced to bukkit / spigot?

**Comment by montlikadani** [comment]
See this line: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/World.java#829

**Comment by aBo0oDyy** [comment]
Thanks for your contribution.

**Pull request merged**
